backend/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<str:username>/', views.profile_update, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

backend/back_ji_hwa/urls.py
from django.contrib import admin
from django.urls import path, include
from django import views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('accounts/', include('dj_rest_auth.urls')),
    path('accounts/signup/', include('dj_rest_auth.registration.urls')),
    path('profile/<str:username>/', views.profile_update, name='profile'),
]

backend/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('',views.movie_list,name = 'movie_list'),
    path('api/movies/', views.fetch_movies, name='fetch_movies'),
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/comments/', views.manage_comment, name='add_comment'),
    path('<int:movie_id>/comments/<int:comment_id>/', 
         views.manage_comment, name='delete_comment'),
    path('<int:movie_id>/ratings/', views.manage_rating, name='manage_rating'),
    path('<int:movie_id>/likes/', views.movie_likes, name='movie_likes'),
    path('origin_movies/',views.get_tmdb_data, name = 'origin_movies'),
   
]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    pass

backend/movies/models.py
from django.db import models
from django.conf import settings  # settings.AUTH_USER_MODEL 사용을 위해 추가

class Movie(models.Model):
    tmdb_id = models.IntegerField(unique=True, null=True, blank=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    director = models.CharField(max_length=100)
    actors = models.CharField(max_length=200)
    age = models.CharField(max_length=50)
    genre = models.CharField(max_length=100)
    runtime = models.IntegerField()
    rates = models.FloatField(default=0)
    is_prized = models.BooleanField(default=False)
    poster_path = models.URLField(max_length=500, null=True, blank=True)  # 포스터 URL 필드 추가

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:50]

class MovieComment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

class MovieLike(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

# 평점 중개 테이블 직접 작성 : 평점 필드가 필요함
class Rate(models.Model):
    rate_user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='user_rated')
    rate_movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    # 사용자가 준 평점 : 추가 필드
    rate_score = models.FloatField()

class Genre(models.Model):
    id = models.IntegerField(primary_key=True) # 장르 id
    name = models.CharField(max_length=50) # 장르 name

backend/accounts/views.py
# from django.contrib.auth import login as auth_login
# from django.contrib.auth import logout as auth_logout
# from django.contrib.auth import update_session_auth_hash
# from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
# from django.contrib.auth.decorators import login_required
# from .forms import CustomUserCreationForm, CustomUserChangeForm


# # Create your views here.
# def login(request):
#     if request.user.is_authenticated:
#         return redirect('movies:movie_list')

#     if request.method == 'POST':
#         form = AuthenticationForm(request, request.POST)
#         if form.is_valid():
#             auth_login(request, form.get_user())
#             return redirect('movies:movie_list')
#     else:
#         form = AuthenticationForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'accounts/login.html', context)


# @login_required
# def logout(request):
#     auth_logout(request)
#     return redirect('movies:movie_list')


# def signup(request):
#     if request.user.is_authenticated:
#         return redirect('movies:movie_list')

#     if request.method == 'POST':
#         form = CustomUserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('movies:movie_list')
#     else:
#         form = CustomUserCreationForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'accounts/signup.html', context)


# @login_required
# def delete(request):
#     request.user.delete()
#     return redirect('movies:movie_list')


# @login_required
# def update(request):
#     if request.method == 'POST':
#         form = CustomUserChangeForm(request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return redirect('movies:movie_list')
#     else:
#         form = CustomUserChangeForm(instance=request.user)
#     context = {
#         'form': form,
#     }
#     return render(request, 'accounts/update.html', context)


# @login_required
# def change_password(request, user_pk):
#     if request.method == 'POST':
#         form = PasswordChangeForm(request.user, request.POST)
#         if form.is_valid():
#             user = form.save()
#             update_session_auth_hash(request, user)
#             return redirect('movies:movie_list')
#     else:
#         form = PasswordChangeForm(request.user)
#     context = {
#         'form': form,
#     }
#     return render(request, 'accounts/change_password.html', context)

# from django.contrib.auth import get_user_model

# def profile(request, username):
#     # 어떤 유저의 프로필을 보여줄건지 유저를 조회 (username을 사용해서 조회)
#     User = get_user_model()
#     person = User.objects.get(username=username)
#     context = {
#         'person': person,
#     }
#     return render(request, 'accounts/profile.html', context)


# def follow(request, user_pk):
#     User = get_user_model()
#     # 팔로우 요청을 보내는 대상
#     you = User.objects.get(pk=user_pk)
#     # 나 (팔로우 요청하는 사람)
#     me = request.user

#     # 나와 팔로우 대상자가 같지 않을 경우만 진행 (다른 사람과만 팔로우 할 수 있음)
#     if me != you:
#     # 만약 내가 상대방의 팔로워 목록에 이미 있다면 팔로우 취소
#         if me in you.followers.all():
#             you.followers.remove(me)
#             # me.followings.remove(you)
#         else:
#             you.followers.add(me)
#             # me.followings.add(you)
#     return redirect('accounts:profile', you.username)

import json
import random
import datetime
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from .serializers.accounts import *
from movies.serializers import *
from rest_framework import status
from rest_framework.permissions import *
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from .serializers.accounts import ProfileSerializer

User = get_user_model()

# 회원가입
# 인증 필요 없이 접근 가능한 영역 : 추후 인증 필요
@api_view(['POST'])
@permission_classes([AllowAny])
def signup(request):
    serializer = AccountSignUpSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
        serializer.save(request)
        return Response(serializer.data, status=status.HTTP_201_CREATED)


# 프로필 정보 조회 및 수정
@api_view(['GET', 'PUT'])
@permission_classes([IsAuthenticated]) # 인증된 사용자만 권한 허용
def profile_update(request, username):
    Users = get_object_or_404(User, username=username)
    if request.user == User:
        serializer = ProfileSerializer(instance=Users, data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            serializer = ProfileSerializer(Users)
            return Response(serializer.data)

# 회원탈퇴
@api_view(['POST'])
@permission_classes([IsAuthenticated]) # 인증된 사용자만 권한 허용
def user_delete(request):
    request.user.delete()
    data = {
            'content': f'{request.user}님의 탈퇴처리가 완료되었습니다.',
        }
    return Response(data, status=status.HTTP_204_NO_CONTENT)


# 사용자가 좋아요/위시리스트/평점을 준 영화 목록 조회
@api_view(['GET'])
@permission_classes([IsAuthenticated]) # 인증된 사용자만 권한 허용
def user_movie_list(request, user_pk):
    Users = get_object_or_404(User, pk=user_pk)
    serializer = UserMovieListSerializer(Users)
    user_list = {
        'id' : serializer.data.get('id'),
        'user_rated_movie_count' : Users.user_rated_movie.count(),
        'user_rated_movie' : serializer.data.get('user_rated_movie'),
        'like_movies_count' : Users.like_movies.count(),
        'like_movies' : serializer.data.get('like_movies'),
        'wish_moives_count' : Users.wish_moives.count(),
        'wish_moives' : serializer.data.get('wish_moives'),
    }
    return JsonResponse(user_list)


# 팔로우 등록 및 해제 : 팔로우 수까지
@api_view(['POST'])
@permission_classes([IsAuthenticated]) # 인증된 사용자만 권한 허용
def follow(request, user_pk):
    # user_pk : 팔로우 하려는 사람의 pk
    follow_user = get_object_or_404(User, pk=user_pk)
    user = request.user
    if follow_user != user:
        if follow_user.followings.filter(pk=user.pk).exists():
            follow_user.followings.remove(user)
            follow = '팔로우' # 현재 버튼을 누르면 발생하는 동작
        else:
            follow_user.followings.add(user)
            follow = '언팔로우' # 현재 버튼을 누르면 발생하는 동작

        serializer = FollowSerializer(follow_user)

        follow_status = {
            'follow' : follow,
            'count' : follow_user.followings.count(), 
            # 팔로워(from_user_id가 팔로우 당한사람 : user_pk)(followings가 팔로우를 한 사람) 목록
            'follow_list' : serializer.data.get('followings'),
            # 팔로잉 수
            'following_count' : follow_user.followers.count(),
        }
    return JsonResponse(follow_status)


# 팔로우 조회
@api_view(['GET'])
@permission_classes([IsAuthenticated]) # 인증된 사용자만 권한 허용
def follow_list(request, user_pk):
    # user_pk : 나의 pk
    follow_user = get_object_or_404(User, pk=user_pk)
    # user = request.user
    # if follow_user.followings.filter(pk=user.pk).exists():
    #     follow_user.followings.remove(user)
    #     follow = '팔로우' # 현재 버튼을 누르면 발생하는 동작
    # else:
    #     follow_user.followings.add(user)
    #     follow = '언팔로우' # 현재 버튼을 누르면 발생하는 동작

    serializer = FollowSerializer(follow_user)

    follow_status = {
        # 팔로워
        'follower_count' : follow_user.followings.count(), 
        # 팔로워(from_user_id가 팔로우 당한사람 : user_pk)(followings가 팔로우를 한 사람) 목록
        'follow_list' : serializer.data.get('followings'),
        # 팔로잉 수
        'following_count' : follow_user.followers.count(),
    }
    return JsonResponse(follow_status)


# 상대방 프로필 조회
@api_view(['GET'])
@permission_classes([IsAuthenticated]) # 인증된 사용자만 권한 허용
def user_profile(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    serializer = UserProfileSerializer(user)
    return Response(serializer.data)

backend/accounts/templates/accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>비밀번호 변경</h1>
  <form action="{% url "change_password" user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

backend/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인</h1>
  <form action="{% url "movies:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

backend/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>{{ person.username }}의 프로필</h1>
  <div>
    팔로잉 : {{ person.followings.all|length }} / 팔로워 : {{ person.followers.all|length }}
  </div>

  {% if request.user != person %}
    <div>
      <form action="{% url "accounts:follow" person.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in person.followers.all %}
          <input type="submit" value="언팔로우">
        {% else %}
          <input type="submit" value="팔로우">
        {% endif %}
      </form>
    </div>
  {% endif %}

  {% comment %} 유저가 작성한 게시글 {% endcomment %}
  <h2>{{ person.username }} 작성한 게시글</h2>
  {% for article in person.article_set.all %}
    <p>{{ article }}</p>
  {% endfor %}

  <hr>

  {% comment %} 유저가 작성한 댓글 {% endcomment %}
  <h2>{{ person.username }} 작성한 댓글</h2>
  {% for comment in person.comment_set.all %}
    <p>{{ comment }}</p>
  {% endfor %}

  <hr>

  {% comment %} 유저가 좋아요한 게시글 {% endcomment %}
  <h2>{{ person.username }} 좋아요한 게시글</h2>
  {% for article in person.like_articles.all %}
    <p>{{ article }}</p>
  {% endfor %}
</body>
</html>

backend/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

backend/accounts/templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원정보 수정</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>